name: todo_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.5.0
  freezed_annotation: ^2.4.1
  go_router: ^17.0.0
  tap_debouncer: ^2.2.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.5.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.6.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/cat.webp