name: todo_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  tap_debouncer: ^2.2.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/cat.webp